import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { languages } from "@/i18n/settings";

const inter = Inter({ subsets: ["latin"] });

type Props = {
	children: React.ReactNode;
	params: {
		locale: string;
	};
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return languages.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }: Props) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
